### PR TITLE
Added memoize function to make program faster and less function calls…

### PR DESCRIPTION
**Pull request by bohorqux**
…, regardless of this change, seems to crash on my computer when doing recursion for values greater than 3.

### CODE REVIEW

**Comment by bohorqux** [comment]
merge this commit you fucker

**Comment by kevakil** [comment]
Can you explain what the memoize function does and briefly how it works? If you could add that explanation to the readme, that'd be nice.

**Comment by kevakil** [comment]
FYI, theres no need to create a new pull request...you can just add another commit to your local repo on your master branch and push.

**Comment by bohorqux** [comment]
cool, just updated the readme and made the commit. So, I'm assuming when I
fork your repository and make changes to my forked repository and push
them, you're able to see the changes correct?

**Comment by kevakil** [comment]
Lovely, thanks.

**Pull request merged**
